package com.goopter.offer.model;

public enum OfferEvent {
    ACCEPT_OFFER, INSTANT_ACCEPT, AUTHORIZE, DECLINE,


    ACCEPTED_OFFER, SELLER_SENT, CARRIER_DELIVERED, BUYER_DECLINED, ITEM_APPROVED_BY_BUYER, PAYMENT_RESERVATION, PAYMENT_TRANSFERRED, SELLER_DECLINED

}
